config/routes.rb
Mobtown::Application.routes.draw do

  match '/category/mob-blog', to: redirect('/mob-blog')
  match '/mob-blog/why-the-century-ballroom-matters--2', to: redirect('/mob-blog/why-the-century-ballroom-matters')
  match '/blues', to: redirect('/dances/blues') # Marissa's postcards

  get "dance_classes/new"

  namespace :ckeditor, :only => [:index, :create, :destroy] do
      resources :pictures
      resources :attachment_files
  end

  root to: 'static_pages#home'
  match '/venue', to: 'static_pages#venue'
  match '/the-location', to: 'static_pages#venue'
  match '/map', to: 'static_pages#map'
  match '/mobmentality', to: 'static_pages#mob_mentality'
  match '/mob-mentality', to: 'static_pages#mob_mentality'
  match '/dances', to: 'static_pages#dances'
  match '/classes/:category/:id', to: 'dance_classes#index'
  resources :dance_classes, :path => '/classes'
  resources :categories, :path => '/class_categories'
  match '/warroom', to: 'application#login'
  match '/war-room', to: 'application#login'
  match '/war', to: 'application#login'
  match '/balls', to: 'application#login'
  match '/admin', to: 'application#login'
  match '/bar', to: 'bulk_signups#new'
  match '/videos', to: 'static_pages#videos'
  resources :staff, :except => [:show]
  resources :events do
    collection do
      get :manage
    end
    resources :occurrences
  end
  resources :passes do
    collection do
      post :bulk_signup
    end
    resources :registrations do
      collection do
        post :checkout
        post :charge
      end
      member do
        get :void
        get :unvoid
      end
    end
  end
  resources :rental_inquiries
  resources :posts, :path => '/mob-blog'
  resources :feature_boxes
  resources :charges
  resources :bulk_signups

  match '/acquire', to: 'static_pages#acquire'
  match '/yelp-example', to: 'static_pages#yelp_example'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include EventHelper
  def home 
    @featured = Occurrence.next(3)
    @carousel = Occurrence.within(2.weeks)
  end

  def yelp_example
    @featured = Occurrence.next(3)
    @carousel = Occurrence.within(2.weeks)
  end

  def venue
  end

  def map
  end

  def mob_mentality
  end

  def calendar
  end

  def dances
  end

  def videos
  end

  def acquire
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/....html.erb
<h1>StaticPages#...</h1>
<p>Find me in app/views/static_pages/....html.erb</p>

app/views/static_pages/_blues.html.erb
<div class="row-fluid">
  <div class="span9 content">
    <%= image_tag 'blues-300.jpg', class: 'pull-left img-rounded' %>
<p>The Mobtown Ballroom is the home of blues dancing in Baltimore, offering dances, workshops, and special events presented by Nevermore Blues, including the Baltimore Blues Summits, Tuesday Blues (now every Tuesday night), and the Baltimore Swing, Soul, &amp; Blues Parties.</p>
<p><strong>Nevermore Blues</strong> aims to support and cultivate blues dancing in Baltimore by offering both new and seasoned dancers opportunities to learn, enjoy great music, and have fun on the dance floor.</p>
<h4>What is blues dancing?</h4>
<p>Blues is a fun, creative, and expressive style of dance that can be done to music in a wide variety of styles and tempos, including high energy Chicago blues, slinky jazz blues, and soulful Delta blues. First developed alongside jazz and blues music during the early 20th century, blues dancing prospered over the years in small, intimate venues like juke joints and house parties, then gained new popularity more recently with the revival of Lindy hop. Modern blues dance is based on vintage styles like Slow Drag and often borrows elements from other dances, like Lindy hop, West Coast Swing, and Argentine tango. Blues is constantly evolving, but is grounded in the fundamentals of partner connection, pulse, improvisation, and musicality.</p>

<p>Keep up with the latest on the <a href="http://www.facebook.com/NevermoreBlues">Nevermore Blues Facebook page</a>.</p>
  </div>
  <div class="signup-well span3">
    <p>On the first Tuesday of every month, dance to the music you love in Baltimore’s new sanctuary for blues and soul.</p>

    <ul>
      <li>9:00 Drop-in Lesson</li>
      <li>9:30pm-12:00am Dance</li>
    </ul>
    <h5>Pricing</h5>
    <p>The dance is $7, and the lesson is included.</p>

    <p>No experience or partner required.</p>
  </div>
</div>

app/views/static_pages/_facebook.html.erb
<div class="fb-like" data-href="https://www.facebook.com/mobtownballroom" data-send="true" data-layout="button_count" data-width="450" data-show-faces="true"></div

app/views/static_pages/_salsa.html.erb
<div class="content">
<%= credited_image_tag 'davis/salsa-300.jpg', credit: 'davis', class: 'pull-left img-rounded' %>
<p>Salsa at the Mobtown Ballroom happens on the first Saturday of the month (with a few exceptions for special events here and there). Spearheaded by the redoubtable Tabitha Holliday, these evenings keep you dancing all night long. As with all of our events, a drop-in lesson happens beforehand. You don't need to bring a partner; you just need to show up ready to have a hell of a good time. $5 per lesson and $5 for the dance.</p>
</div>

app/views/static_pages/_weekly_swing.html.erb
<div class="row-fluid">
  <div class="span9 content">
    <%= credited_image_tag 'munchel/michael-nina-pose-300.jpg', credit: 'munchel', class: 'img-rounded pull-left' %>
    <p>Our regular Monday and Friday dances go on as late you want to stay. No experience or partner required.</p>
    <h5>Mondays</h5>
    <ul>
      <li>8-9 Drop-in Beginner Lesson</li>
      <li>9-11:30 Swing &amp; Lindy Hop Dance</li>
    </ul>

    <h5>Fridays</h5>
    <ul>
      <li>8-9 Drop-in Beginner Lesson</li>
      <li>9-late Swing &amp; Lindy Hop Dance</li>
    </ul>
  </div>
  <div class="signup-well span3">
    <h5>Pricing</h5>
    <p>Drop-in lessons are $5. Monday dances are $5; Fridays are $7.
    <p>When we bring in live bands, pricing changes. See event announcements for details.</p>
  </div>
</div>

app/views/static_pages/_west_coast.html.erb
<div class="content">
<%= image_tag 'west-coast-300.jpg', class: 'pull-left img-rounded' %>
<p>West Coast Swing is a new addition to the Mobtown lineup, and much like the fabled chupacabra, our WCS night strikes irregularly and without warning, so pay attention. Our next night will be Sunday, April 27th. West Coast is a smooth and sexy dance done to a huge variety of music. Our Sunday night dances have become highly prized for the laid-back atmosphere, perfect dance floor, and top-notch instruction. Check the events page for details. $10 gets you the dance and lesson.</p>
</div>

app/views/static_pages/_yelp.html.erb
<%
require 'oauth'
require 'json'

consumer_key = 'vm3mrkUPUQdQYEZYrBoVyw'
consumer_secret = 'jIZFg2HGmbKAzEBE6kkVEc6CniU'
token = '928iTJ6MeALkqH-m4kKhWr8URnlPQvCn'
token_secret = 'uriiKDrX8l0qiwIafGykD9Ut5qI'

api_host = 'api.yelp.com'

consumer = OAuth::Consumer.new(consumer_key, consumer_secret, {:site => "https://#{api_host}"})
access_token = OAuth::AccessToken.new(consumer, token, token_secret)

path = "/v2/business/the-mobtown-ballroom-baltimore"
hash = JSON.parse access_token.get(path).body
%>

<%= link_to image_tag('tiny-yelp-icon.png'), 'https://www.yelp.com' %> 
<%= link_to image_tag(hash['rating_img_url']) + ' ' + hash['review_count'].to_s + ' reviews', hash['url'] %>

<% rescue SocketError %>

app/views/static_pages/acquire.html.erb
<iframe width='500' height='300' frameborder='0' src='https://docs.google.com/spreadsheet/pub?key=0Ai-Y0A0VdIVgdDgxdU1YOVI5NGM5RXN6NTdrbkNzZmc&single=true&gid=0&output=html&widget=true'></iframe>

app/views/static_pages/calendar.html.erb
<iframe src="https://www.google.com/calendar/embed?src=s6m2494bvo05cb01jf2r5a2gt8%40group.calendar.google.com&ctz=America/New_York" style="border: 0; background-color: #91B0AC;" width="100%" height="600" frameborder="0" scrolling="no"></iframe>

app/views/static_pages/dances.html.erb
<h4>Regular Dance Events</h4>

<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs" id="dances">
    <li><a href="#swing" data-toggle="tab">Monday & Friday Swing</a></li>
    <li><a href="#blues" data-toggle="tab">Soul & Blues</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane" id="swing">
      <%= render 'static_pages/weekly_swing' %>
    </div>
    <div class="tab-pane active" id="blues">
      <%= render 'static_pages/blues' %>
    </div>
  </div>
</div>

<% content_for :javascript do %>
<script>
$('#dances').click(function(e) {
    e.preventDefault();
    $(this).tab('show');
})

$('#dances a:first').tab('show');
</script>
<% end %>

<% content_for :title, 'Dance Nights' %>

app/views/static_pages/home.html.erb
<div id="heroCarousel" class="carousel slide">
  <!-- Carousel items -->
  <div class="carousel-inner">
  <% @is_first = true %>
  <% @carousel.each do |occurrence| %>
    <% event = Event.find(occurrence.event_id) %>
    <div class="item <%= @is_first? 'active' : '' %>">
      <% @is_first = false %>
      <div class="overflow-box">
        <% if event.prose.blank? and event.link.nil? %>
          <%= image_tag event.photo.url(:carousel), :size => '700x450' %>
          <div class="carousel-caption">
            <p>
            <span class="event-header">
              <%= content_tag :span, occurrence.start.strftime("%A, %b %e"), class: 'event-date' %>
              <%= content_tag :span, event.name, class: 'event-title' %>
            </span>
            <%= raw event.summary %></p>
          </div>
        <% else %>
        <% link = event.link.nil? ? event_path(event) : event.link %>
          <%= link_to(link) do %>
            <%= image_tag event.photo.url(:carousel), :size => '700x450' %>
            <div class="carousel-caption">
              <p>
              <span class="event-header">
                <%= content_tag :span, occurrence.start.strftime("%A, %b %e"), class: 'event-date' %>
                <%= content_tag :span, event.name, class: 'event-title' %>
              </span>
              <%= raw event.summary %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#heroCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#heroCarousel" data-slide="next">&rsaquo;</a>
</div>

  <div class="row-fluid">
    <div class="span4 feature-box">
      <%= link_to content_tag(:h3, 'Upcoming Events', class: 'headline'), events_path %>
      <%= render partial: 'events/featured', collection: @featured, as: :occurrence %>
      <%= link_to "More Events & Details", events_path, class: "btn btn-dirtydog" %>

    </div>
    <div class="span4 feature-box">
      <h3 class="headline"><%= link_to 'Learn to Dance', dance_classes_path %></h3>
      <p>We have a bullet-proof proof curriculum to get you started quickly. You're in good hands.</p>
      <!-- NOTHIng! -->
      <%= link_to "Sign Up", dance_classes_path, class: "btn btn-dirtydog" %>
    </div>
    <div class="span4 feature-box">
      <h3 class="headline"><%= link_to 'Read Our Manifesto', mobmentality_path %></h3>
      <p>The mob has spoken. Find out why Mobtown is a big deal.</p>
      <%= link_to 'The Mob Mentality', mobmentality_path, class: 'btn btn-dirtydog' %>
      <div style="margin-top: 20px">
        <div class='pull-left' style='margin-right: 20px; margin-bottom: 10px;'><%= image_tag 'bob-2013_100.png' %></div>
        <div><%= render 'facebook' %></div>
        <div><%= render 'yelp' %></div>
      </div>
    </div>
  </div>

<% content_for :javascript do %>
  <script>
      $(document).ready(function(){
        $('.carousel').carousel({
          interval: 5000
        });
      });
  </script>
<% end %>
<% content_for :top_body do %>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=492733420758797";
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
  </script>
<% end %>

app/views/static_pages/map.html.erb
<p>We are working on some deals to secure a parking lot in the evening, but for now, all parking is street parking. If you can’t find a spot on Washington Boulevard, we recommend that you head North rather than South. Carpool and show up early, as parking doesn’t usually become a problem before 9:30, and is never a problem on class nights.</p>

<div class="center">
<iframe src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=861+Washington+Boulevard,+Baltimore,+MD&amp;aq=0&amp;sll=37.0625,-95.677068&amp;sspn=54.093296,79.013672&amp;vpsrc=0&amp;ie=UTF8&amp;hq=&amp;hnear=861+Washington+Blvd,+Baltimore,+Maryland+21230&amp;t=h&amp;z=14&amp;ll=39.282938,-76.630908&amp;output=embed" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" width="700" height="660"></iframe>
</div>

<% content_for :title, 'Map' %>

app/views/static_pages/mob_mentality.html.erb
<h3>The Mob Mentality</h3>

<div class="content">
<h4>We like our fun to be social.</h4>
<p>This means that no one passively consumes at the Mobtown Ballroom. We like to sit back with a beer and watch SVU marathons as much as anyone else, but we really get our kicks by going out, meeting people, dancing, and bullshitting face to face. A ballroom is really just an open space, it’s what the people do inside that makes it something special.
<%= credited_image_tag 'davis/Halloween_2012_02-300.jpg', credit: 'davis', class: 'pull-left img-rounded' %>
We teach a whole lot of dance classes (and we do it damn well) but the point of our classes is not to make money or feel good about being teachers—we teach classes to get as many people on the dance floor as possible. Our dances are the main event, and we live for them. We combine kick-ass dancing with good times and conversation. We like to sing karaoke. We like to dance with beginners. We like to have incredibly wild house parties. This is why the Mobtown Ballroom is not a dance studio. But there is another element. This place isn’t a traditional club. When you show up, you will meet a lot of people, but they don’t come to hook up (at least primarily); they come to dance. While we’ll get you started shockingly quickly, the dances we do here can take a lifetime to master. They’re fun to do and they are fun to watch. More than this, they are partner dances, which means that you spend time dancing with a variety of people every night. This is part of the fun, because, unlike other social outlets, the focus is on the activity itself. You get to know people in the context of a shared activity that you work on continuously. You will make friends&#8211;hell, you might get married, but whatever happens you are going to enjoy yourself.</p>
<h4>We like our fun to be inclusive.</h4>
<p>The Mobtown Ballroom is about dancing, meeting people, and having a good time. As soon as we walk through the doors we don’t care about anything else. We do our best to cultivate an energized atmosphere that is not only welcoming to everyone but rabidly enthusiastic. We like new people and we like dancing with new people. If you show up, and stand on the edge of the floor, someone is going to ask you to dance. It doesn’t matter if you’re a beginner or an old pro. We don’t care about your politics, your race, your sexual orientation, your religion, or anything else, and we don’t tolerate any kind of harassment. Whoever you are or wherever you’re from, if you want to dance, you’re in the right place.</p>
<h4>We like our fun to be swanky.</h4>
<p>We have a venue that you have to see to believe. This place is beautiful, and on band nights when everyone is dressed up, The Mobtown Ballroom is a sight to behold.</p>
<h4>We don&#8217;t take ourselves too seriously.</h4>
<%= credited_image_tag 'davis/June2012_18-300.jpg', credit: 'davis', class: 'pull-right img-rounded' %>
<p>We like mayhem. Towards the end of the night on swing nights, we tend to get a little goofy with the music and keep things open late. It has been known to stay open well past 2:00 a.m. and devolve into a full-on, top-40 dance party. Some times you just have to swing out to Lady Gaga. On Friday nights we have silly contests (crabwalk, chorus-line kicks, arm-wrestling, etc.) This keeps things from getting snooty and sets the right mood. I have it on good authority that it is technically impossible to to be in a bad mood while crab-walking.</p>
<h4>We like our fun to be adult.</h4>
<p>This isn&#8217;t as dirty as it sounds. People spend most of their time in censorious environments (like work or school), trying to appear well-mannered and bland. That&#8217;s what the day is for. Come to our evening programming and you can hoot and hollar at sexy performances, dance dirtier than Patrick Swayze, have an incredibly strong drink at the Calypso Cafe down the road, or contemplate our stained-glass windows and pray. It&#8217;s grown up time, and a dash of benign anarchy helps take the edge off the work week.</p>
<h4>We like our fun to be cheap.</h4>
<p>This is a great place, and it is steadily growing, so we can afford to rely on volume rather than price hikes. A normal weekly dance runs you between $5 and $7, and last from 4-5 hours.  On top of all of this, dancing is actually good for you (although you won't be thinking about that while you're doing it). The Mobtown Ballroom is not a non-profit. We won't ask you for donations. We’re not trying to make you cultured or distinguished. We're trying to entertain you.</p> 
</div>
<% content_for :title, 'The Mob Mentality' %>

app/views/static_pages/venue.html.erb
<div class="img-rounded content">
<h4>The Skinny</h4>
<p>THE MOBTOWN BALLROOM, located in historic Pigtown, is Baltimore’s premiere location for social dance events, dance classes, live music, conferences, weddings, and general mayhem. We host belly dance, burlesque, art shows, and pretty much everything you could want in an evening out. We restored a beautiful 1870s church with a 2,500 square foot sprung dance floor and a 1,200 square foot stage.</p>


<h4>Rental Information</h4>
<%= credited_image_tag 'munchel/curtains-300.jpg', credit: 'munchel', class: "img-rounded pull-left" %>
<p>The Mobtown Ballroom is available for weddings, parties, conferences, and a wide array of events. We have retained the original splendor of this 19th century church, while making some improvements, including the installation of a gorgeous, 3,000 square-foot oak floor (the best dance floor on the East Coast), the construction of a beautiful oak bar and sound booth (both of which were salvaged from original church furniture), and some of the most powerful air-conditioning known to man.  All of our alterations were made using repurposed materials within the building, leaving this space with a classic and flexible elegance.</p>

<p>The Mobtown Ballroom is not affiliated with any religion and welcomes all regardless of race, gender, class, or sexual orientation. Whether you want to dance, host a birthday party, or get married, our doors are open.</p>

<h4>Weddings (Gay, Straight, or Otherwise)</h4>
<%= credited_image_tag "munchel/brightly-lit-tables-300.jpg", credit: 'munchel', class: "pull-right img-rounded" %>
<p>We have an experienced team on hand to help make your wedding happen in our space. The Ballroom has some of the beauty and transcendent elegance of a traditional church combined with the functionality of a theatre and entertainment center. It thus serves perfectly for both the wedding and the reception.  Email <a href="mailto:mobtownballroom@gmail.com">mobtownballroom@gmail.com</a> to schedule a walkthrough, or call (443) 699-3040.</p>

<h4>Amenities</h4>
<p>All rentals include the use of a the sound-system and our stage and floor lights. We have 25 cafe-style round tables with burgundy or white table clothes, 150 burgundy and gold chairs, and pew seating for up to 40 people. Behind our beautiful bar we have a selection of soft drinks and bottled water/juice available for sale. Any rental includes the use of all of this and the presence of at least one staff member to deal with any problems that may arise.</p>

<h4>Rates and Availability</h4>
<%= credited_image_tag "munchel/bar-300.jpg", credit: 'munchel', class: "pull-left img-rounded" %>
<p>The Ballroom is never available for rental on Monday or Friday nights. Saturday and Sunday evening rentals run between $800-$3,000 depending on the number of staff persons required, and the level of back-end work necessary on our end. Weekday nights are negotiable as are daytime rentals during the week. We try to keep our clients&#8217; options open to make the space available for a wide variety of purposes, and we are willing to work with you to provide the perfect event on your budget. We are currently looking for weekday 9-5 rentals, and will provide a very reasonable price to long-term renters.</p>

<p>We have a full schedule, so inquire far in advance. Contact <a href="mailto:smobtownballroom@gmail.com">mobtownballroom@gmail.com</a> for rates and availability.</p>
</div><!-- content -->
<% content_for :title, 'The Venue' %>