config/routes.rb
Mobtown::Application.routes.draw do

  match '/category/mob-blog', to: redirect('/mob-blog')
  match '/mob-blog/why-the-century-ballroom-matters--2', to: redirect('/mob-blog/why-the-century-ballroom-matters')
  match '/blues', to: redirect('/dances/blues') # Marissa's postcards

  get "dance_classes/new"

  namespace :ckeditor, :only => [:index, :create, :destroy] do
      resources :pictures
      resources :attachment_files
  end

  root to: 'static_pages#home'
  match '/venue', to: 'static_pages#venue'
  match '/the-location', to: 'static_pages#venue'
  match '/map', to: 'static_pages#map'
  match '/mobmentality', to: 'static_pages#mob_mentality'
  match '/mob-mentality', to: 'static_pages#mob_mentality'
  match '/dances', to: 'static_pages#dances'
  match '/classes/:category/:id', to: 'dance_classes#index'
  resources :dance_classes, :path => '/classes'
  resources :categories, :path => '/class_categories'
  match '/warroom', to: 'application#login'
  match '/war-room', to: 'application#login'
  match '/war', to: 'application#login'
  match '/balls', to: 'application#login'
  match '/admin', to: 'application#login'
  match '/bar', to: 'bulk_signups#new'
  match '/videos', to: 'static_pages#videos'
  resources :staff, :except => [:show]
  resources :events do
    collection do
      get :manage
    end
    resources :occurrences
  end
  resources :passes do
    collection do
      post :bulk_signup
    end
    resources :registrations do
      collection do
        post :checkout
        post :charge
      end
      member do
        get :void
        get :unvoid
      end
    end
  end
  resources :rental_inquiries
  resources :posts, :path => '/mob-blog'
  resources :feature_boxes
  resources :charges
  resources :bulk_signups

  match '/acquire', to: 'static_pages#acquire'
  match '/yelp-example', to: 'static_pages#yelp_example'

end

app/controllers/dance_classes_controller.rb
class DanceClassesController < ApplicationController
  before_filter :authenticate, :except => [:index, :show]

  def new
    @dance_class = DanceClass.new
    @dance_class.passes.build
 
    respond_to do |format|
      format.html  # new.html.erb
      format.json  { render :json => @dance_class }
    end
  end

  def create
    @dance_class = DanceClass.new(params[:dance_class])
 
    respond_to do |format|
      if @dance_class.save
        format.html  { redirect_to(@dance_class,
                      :notice => 'Class was successfully created.') }
        format.json  { render :json => @dance_class,
                      :status => :created, :location => @dance_class }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @dance_class.errors,
                    :status => :unprocessable_entity }
      end
    end
  end

  def index
    @charge = Charge.new
    @category_id = params.has_key?(:category) ? params[:category] : 2 
    @category = Category.find(@category_id)
    @dance_classes = @category.dance_classes
    if params.has_key?('id')
      @tab = '[href="#tab-' + params[:id] + '"]'
    else
      @tab = ':first'
    end
    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @dance_classes }
    end
  end

  def edit
    @dance_class = DanceClass.find(params[:id])
    @dance_class.passes.build
  end

  def update
    @dance_class= DanceClass.find(params[:id])
 
    respond_to do |format|
      if @dance_class.update_attributes(params[:dance_class])
        format.html  { redirect_to(@dance_class,
                      :notice => 'Dance Class was successfully updated.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @dance_class.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  def show
    @charge = Charge.new
    @category = DanceClass.find(params[:id]).category
    @dance_classes = @category.dance_classes
    @tab = '[href="#tab-' + params[:id] + '"]'

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @dance_classes }
    end
  end

  def destroy
    @dance_class = DanceClass.find(params[:id])
    @dance_class.destroy
 
  respond_to do |format|
    format.html { redirect_to dance_classes_url }
    format.json { head :no_content }
  end
end
end

app/helpers/dance_class_helper.rb
module DanceClassHelper
end

app/helpers/dance_classes_helper.rb
module DanceClassesHelper
end

app/views/dance_classes/_all_classes_menu.html.erb
    <ul class="nav nav-list">
    <% Category.all.each do |category| %>
      <li class="nav-header"><%= category.name %></li>
      <% category.dance_classes.each do |dance_class| %>
        <li><%= link_to dance_class.name, dance_class_path(dance_class) %></li>
      <% end %>
    <% end %>
    </ul>

app/views/dance_classes/_belly_dancing.html.erb
<h4>Belly Dancing</h4>

<%= credited_image_tag 'munchel/belly-dancing-michelle-300.jpg', credit: 'munchel', class: 'img-rounded pull-left' %>
<p>Nina Gilkenson is a world-class dance teacher, competitor and choreographer who brings a sense of graceful fun to everything she does. The Mobtown Ballroom is proud to announce that she will now be teaching Belly Dance classes on Tuesday nights. Nina employs musical variety and a mixture of styles to help you become a versatile and interesting dancer.</p>

<p>Unlike other Belly Dance classes, Nina's program does not require that you participate in a performance. There are certainly opportunities to perform, but we realize that people take Belly Dancing for a variety of reasons: Some want to train for other disciplines, some want to perform, some want to get fit, and some aren’t quite sure yet. That's okay here.</p>

app/views/dance_classes/_content.html.erb
<div class="row-fluid">
  <div class="span9 content">
    <h4><%= @category.name %></h4>
    <%= raw @category.prose %>
    <% if logged_in? %>
      <p class="war-room">War Room: <%= link_to 'Edit This Category Description', edit_category_path(@category) %>
    <% end %>
    <div class="tabbable row-fluid clear-left">
      <ul class="nav nav-tabs" id="dance-classes">
        <% @dance_classes.each do |dance_class| %>
        <li><a href="#tab-<%= dance_class.friendly_id %>" data-toggle="tab"><%= dance_class.name %></a></li>
        <% end %>
      </ul>
      <div class="tab-content span12">
        <% @dance_classes.each do |dance_class| %>
        <div class="tab-pane row-fluid" id="tab-<%= dance_class.friendly_id %>">
          <div class="span8 min-width-youtube">
            <%= yield :dance_class %>
            <p><%= dance_class.description.html_safe %></p>
          </div>
          <div class="signup-well span4">
            <% if not dance_class.passes.active.empty? %>
              <%= render :template => 'registrations/new', :locals => {:passes => dance_class.passes.active} %>
            <% else %>
              <p>Registration is not currently open. Check back later on, or <%= link_to 'email us', 'mailto:mobtownballroom@gmail.com' %>to enquire.</p>.
            <% end %>
          </div>
        <% if logged_in? %>
          <p class='war-room'>War Room: <%= link_to 'Edit or Destroy', edit_dance_class_path(dance_class) %></p>
        <% end %>
        </div>
        <% end %>
      </div><!-- tab-content -->
      <% if logged_in? %>
        <p class="war-room">War Room: <%= link_to 'New Class', new_dance_class_path %></p>
      <% end %>
    </div>
  </div>

  <div class="span3" id="all-dance-classes">
    <%= render 'all_classes_menu' %>
  </div>

  <% content_for :javascript do %>
    <script>
      $('#dance-classes a').click(function(e) {
        e.preventDefault();
        $(this).tab('show');
      })  
      $('#dance-classes a<%=raw @tab %>').tab('show');

      document.getElementById("classes-nav-element").className += "active";
    </script>
  <% end %>

</div><!-- row-fluid -->
<% content_for :title, 'Dance Classes' %>

app/views/dance_classes/_form.html.erb
<%= simple_form_for @dance_class, html: {class: 'form-horizontal'} do |f| %>
  <% if @dance_class.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@dance_class.errors.count, "error") %> prohibited
        this class from being saved:</h2>
    <ul>
    <% @dance_class.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <%= f.input :name %>
  <%= f.input :category_id, collection: Category.all %>
  <div class="control-group"><div class="control-label">or create a new category called</div><div class="controls"><%= f.text_field :new_category_name %></div></div>
  <%= f.input :description, :as => :ckeditor %>
  <%= content_tag :legend, 'Passes' %>
  <%= f.simple_fields_for 'passes' do |p| %>
    <%= render 'passes/fields', f: p %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/dance_classes/_lindy.html.erb
<h4>Lindy Hop</h4>

<%= image_tag 'michael-nina-300.jpg', class: 'img-rounded pull-left' %>

<p>At the Mobtown Ballroom we offer regular six-week series in Lindy Hop and East Coast Swing. Lindy Hop is the most interesting, complex, and expressive of the swing dances, and can be danced to a wide range of musical styles and tempos. Developing out of Charleston in the 1920s Lindy hop incorporates a number of other dances, and has endless opportunities for improvisation and development. Everyone has a different style, and everyone can dance with each other.</p>

<p>All of our regular Swing and Lindy Hop classes are taught by Nina Gilkenson and Michael Seguin. Nina is a world-famous instructor and spends most of her weekends travelling the world teaching Lindy Hop, Belly Dance, and Burlesque. Michael has been building local dance scenes since 2000, and has developed a bullet-proof syllabus that combines enough repetition and variety to make sure that you get something new out of every class. The point is: You’re in good hands.</p>

app/views/dance_classes/_salsa.html.erb
<h4>Salsa</h4>

<p>We teach regular Salsa classes at the Mobtown Ballroom, and we have a Salsa dance on the first Saturday of each month.</p>

<p>We cultivate a relaxed and beginner friendly atmosphere for our Salsa programming at the Ballroom. No partner is required, and people are here to dance. It's not a traditional club/pickup scene.</p>

app/views/dance_classes/_swing.html.erb
<h4>East Coast Swing Dancing</h4>

<%= credited_image_tag 'davis/charlie-uyum-300.jpg', credit: 'davis', class: 'img-rounded pull-left' %>

<p>At the Mobtown Ballroom we offer regular six-week series in Lindy Hop and East Coast Swing. East Coast Swing is a later development and is composed of the simpler, 6-count elements of Lindy Hop. All of our Lindy classes are offered at the absolute beginner level, but East Coast Swing offers an option for those who are either dipping their toe in the water or want to take the class simultaneously with Lindy 1 to get a jump start on 6-count material.</p>

<p>The Mobtown Ballroom is committed to making it as easy as possible to get started dancing, which is why we offer a drop in lesson at 8:00 on every Monday and Friday before our main swing dances. The drop-in is $5 and gives you everything you need to start dancing immediately. Try it out to see if you'd like to take a full-on series.</p>

<p>All of our regular Swing and Lindy Hop classes are taught by Nina Gilkenson and Michael Seguin. Nina is a world-famous instructor and spends most of her weekends travelling the world teaching Lindy Hop, Belly Dance, and Burlesque. Michael has been building local dance scenes since 2000, and has developed a bullet-proof syllabus that combines enough repetition and variety to make sure that you get something new out of every class. The point is: You’re in good hands.</p>

app/views/dance_classes/_west_coast.html.erb
<h4>West Coast Swing</h4>

<p>New programming!</p>

app/views/dance_classes/edit.html.erb
<h1>Editing Class</h1>
 
<%= render 'form' %>
 
<%= link_to 'Destroy', @dance_class, :confirm => 'Pull the trigger?',
                                     :method => :delete %>

<% content_for :title, 'Edit ' + @dance_class.name %>

app/views/dance_classes/index.html.erb
<%= render 'dance_classes/content' %>

app/views/dance_classes/new.html.erb
<h3>New Class</h3>
 
<%= render 'form' %>
<% content_for :title, 'New Class' %>

app/views/dance_classes/show.html.erb
<%= render 'dance_classes/content' %>