config/routes.rb
Mobtown::Application.routes.draw do

  match '/category/mob-blog', to: redirect('/mob-blog')
  match '/mob-blog/why-the-century-ballroom-matters--2', to: redirect('/mob-blog/why-the-century-ballroom-matters')
  match '/blues', to: redirect('/dances/blues') # Marissa's postcards

  get "dance_classes/new"

  namespace :ckeditor, :only => [:index, :create, :destroy] do
      resources :pictures
      resources :attachment_files
  end

  root to: 'static_pages#home'
  match '/venue', to: 'static_pages#venue'
  match '/the-location', to: 'static_pages#venue'
  match '/map', to: 'static_pages#map'
  match '/mobmentality', to: 'static_pages#mob_mentality'
  match '/mob-mentality', to: 'static_pages#mob_mentality'
  match '/dances', to: 'static_pages#dances'
  match '/classes/:category/:id', to: 'dance_classes#index'
  resources :dance_classes, :path => '/classes'
  resources :categories, :path => '/class_categories'
  match '/warroom', to: 'application#login'
  match '/war-room', to: 'application#login'
  match '/war', to: 'application#login'
  match '/balls', to: 'application#login'
  match '/admin', to: 'application#login'
  match '/bar', to: 'bulk_signups#new'
  match '/videos', to: 'static_pages#videos'
  resources :staff, :except => [:show]
  resources :events do
    collection do
      get :manage
    end
    resources :occurrences
  end
  resources :passes do
    collection do
      post :bulk_signup
    end
    resources :registrations do
      collection do
        post :checkout
        post :charge
      end
      member do
        get :void
        get :unvoid
      end
    end
  end
  resources :rental_inquiries
  resources :posts, :path => '/mob-blog'
  resources :feature_boxes
  resources :charges
  resources :bulk_signups

  match '/acquire', to: 'static_pages#acquire'
  match '/yelp-example', to: 'static_pages#yelp_example'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :get_special_events

  def get_special_events
    @special_events = Event.special.upcoming
  end

  def login
    authenticate
    @events = Event.all
    @dance_classes = DanceClass.all
    @latest_rental_inquiry = RentalInquiry.order('created_at DESC').first
  end

  protected
    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == AUTH[:admin_user] && password == AUTH[:admin_password]
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
    not request.authorization.nil?
  end

  def credited_image_tag (source, options={})
    content_tag(:figure, class: options[:class]) do
      image_tag(source, class: options[:class]) +
      content_tag(:figcaption) do
        render 'credit/' + options[:credit]
      end
    end
  end

  # prints numeric date, as in 12/25/2013
  def shortDate(obj)
    obj.strftime("%m/%d/%Y")
  end

end

app/views/application/_paypal.html.erb
<form target="paypal" action="https://www.paypal.com/cgi-bin/webscr" method="post" class="paypal">
  <!-- Identify your business so that you can collect the payments. -->
  <input type="hidden" name="business" value="mobtownballroom@gmail.com">
  <!-- Specify a PayPal Shopping Cart Add to Cart button. -->
  <input type="hidden" name="cmd" value="_cart">
  <input type="hidden" name="add" value="1">
  <!-- Specify details about the item that buyers will purchase. -->
  <% name = defined?(item.name) ? item.name : item.title # Hack! %>
  <input type="hidden" name="item_name" value="<%= name %>" />
  <input type="hidden" name="amount" value="<%= item.price %>" />
  <input type="hidden" name="currency_code" value="USD" />
  <% if not item.student_price.blank? %>
    <input name="on0" type="hidden" value="student" />
    <select name="os0" class="student">
      <option value="no">Adult - <%= number_to_currency(item.price) %></option>
      <option value="yes">Student - <%= number_to_currency(item.student_price) %></option>
    </select>
    <input type="hidden" name="option_select0" value="no" />
    <input type="hidden" name="option_select1" value="yes" />
    <input type="hidden" name="option_amount0" value="<%= item.price %>" />
    <input type="hidden" name="option_amount1" value="<%= item.student_price %>" />
  <!-- Specify where customers return if order succeeds or is canceled. -->
  <% end %>
  <!-- Display the payment button. -->
  <input type="submit" name="submit" class="btn btn-dirtydog" value="Register" alt="PayPal - The safer, easier way to pay online" />
</form>

app/views/application/login.html.erb
<div>
<%= content_tag(:h4, 'Rental Inquiries') %>
<% if @latest_rental_inquiry then %>
  <%= content_tag :p, 'Latest rental inquiry received on ' + (shortDate @latest_rental_inquiry) %>
  <%= link_to 'View Rental Inquiries', rental_inquiries_path, class: 'btn' %>
<% else %>
  <p>There have been no rental inquiries.</p>
<% end %>
</div>
<%= link_to content_tag(:i, '', class: 'icon-plus') + ' New Event', new_event_path, class: 'btn pull-right' %>
<%= content_tag(:h4, 'Events') %>
<table class='table ruled table-hover'>
  <tbody>
  <% @events.sort_by{|e| -e.passes.active.count}.each do |event| %>
    <%= content_tag :tr do %>
      <%= content_tag :td do %>
        <%= link_to(content_tag(:h5, event.name), edit_event_path(event)) %>
        <% if event.occurrences.empty? %>
          <p class='note'>No scheduled occurrences. This event is dormant, kept for future reuse.</p>
        <% else %>
          <p class='note'>Scheduled <%= event.occurrences.collect{|o| o.start}.to_sentence %> 
          </p>
        <% end %>
        <% if event.passes.empty? %>
          <p class='note'>No passes</p>
        <% else %>
           
          <table class='table-bordered ruled'>
          <% event.passes.sort_by{|p| [-p.price, p.name]}.each do |pass| %>
            <tr>
              <%= content_tag :td, pass.name %>
              <%= content_tag :td, number_to_currency(pass.price) %>
              <%= content_tag :td  do %>
                <%= content_tag(:strong, pass.registrations.not_void.count) %>
                <%= pass.limit.blank? ? ' sold' : ' / ' + pass.limit.to_s + ' sold' %>
              <% end %>
              <%= content_tag :td, number_to_currency(pass.paid_online) + ' online' %>
              <%= content_tag :td, number_to_currency(pass.paid_by_card) + ' by card' %>
              <%= content_tag :td, number_to_currency(pass.paid_in_cash) + ' in cash' %>
              <%= content_tag :td, number_to_currency(pass.paid_on_tab) + ' on tab' %>
              <%= content_tag :td, number_to_currency(pass.paid_total) + ' total' %>
              <%= pass.registrations.empty? ? content_tag(:td, 'No Registrants') : content_tag(:td, link_to('View Registration List', pass_registrations_path(pass), class: 'btn')) %>
              <%= content_tag :td, pass.status %>
            </tr>
          <% end %>
          <% if event.passes.count > 1 %>
            <tr>
              <td>Totals</td>
              <td></td>
              <td></td>
              <%= content_tag :td, number_to_currency(event.passes.collect{|p| p.paid_online}.sum) %>
              <%= content_tag :td, number_to_currency(event.passes.collect{|p| p.paid_by_card}.sum) %>
              <%= content_tag :td, number_to_currency(event.passes.collect{|p| p.paid_in_cash}.sum) %>
              <%= content_tag :td, number_to_currency(event.passes.collect{|p| p.paid_on_tab}.sum) %>
              <%= content_tag :td, number_to_currency(event.passes.collect{|p| p.paid_total}.sum) %>
              <td></td>
              <td></td>
            </tr>
          <% end %>
          </table>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  </tbody>
</table>
<br />
<%= link_to content_tag(:i, '', class: 'icon-plus') + ' New Class', new_dance_class_path, class: 'btn pull-right' %>
<%= content_tag :h4, 'Classes' %>
<table class='table ruled table-hover'>
  <tbody>
  <% @dance_classes.sort_by{|d| [d.created_at, -d.passes.active.count]}.each do |event| %>
    <%= content_tag :tr do %>
      <%= content_tag :td do %>
        <%= link_to(content_tag(:h5, event.name), edit_dance_class_path(event)) %>
        <% if event.passes.empty? %>
          <p class='note'>No passes</p>
        <% else %>

          <table class='table-bordered ruled'>
          <% event.passes.sort_by{|p| [-p.price, p.name]}.each do |pass| %>
            <tr>
              <%= content_tag :td, pass.name %>
              <%= content_tag :td, number_to_currency(pass.price) %>
              <%= content_tag :td  do %>
                <%= content_tag(:strong, pass.registrations.not_void.count) %>
                <%= pass.limit.blank? ? ' sold' : ' / ' + pass.limit.to_s + ' sold' %>
              <% end %>
              <%= content_tag :td, number_to_currency(pass.paid_online) + ' online' %>
              <%= content_tag :td, number_to_currency(pass.paid_by_card) + ' by card' %>
              <%= content_tag :td, number_to_currency(pass.paid_in_cash) + ' in cash' %>
              <%= content_tag :td, number_to_currency(pass.paid_on_tab) + ' on tab' %>
              <%= content_tag :td, number_to_currency(pass.paid_total) + ' total' %>
              <%= pass.registrations.empty? ? content_tag(:td, 'No Registrants') : content_tag(:td, link_to('View Registration List', pass_registrations_path(pass), class: 'btn')) %>
              <%= content_tag :td, pass.status %>
            </tr>
          <% end %>
          <% if event.passes.count > 1 %>
            <tr>
              <td>Totals</td>
              <td></td>
              <td></td>
              <%= content_tag :td, number_to_currency(event.passes.collect{|p| p.paid_online}.sum) %>
              <%= content_tag :td, number_to_currency(event.passes.collect{|p| p.paid_by_card}.sum) %>
              <%= content_tag :td, number_to_currency(event.passes.collect{|p| p.paid_in_cash}.sum) %>
              <%= content_tag :td, number_to_currency(event.passes.collect{|p| p.paid_on_tab}.sum) %>
              <%= content_tag :td, number_to_currency(event.passes.collect{|p| p.paid_total}.sum) %>
              <td></td>
              <td></td>
            </tr>
          <% end %>
          </table>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  </tbody>
</table>
<%= link_to content_tag(:i, '', class: 'icon-plus') + ' New Mob Blog Post', new_post_path, class: 'btn' %>